cluster.name: mda-cluster
node.name: mda-es-01
network.host: 0.0.0.0
http.port: 9200

discovery.type: single-node

xpack.security.enabled: false
xpack.security.http.ssl.enabled: false

indices.query.bool.max_clause_count: 4096

action.auto_create_index: true
