--log-level=WARNING
--storage-properties-on-edges=true
--storage-wal-enabled=true
--storage-snapshot-interval-sec=300
--storage-snapshot-retention-count=3
--storage-wal-file-size-kib=65536
--query-execution-timeout-sec=300
--bolt-num-workers=16
--bolt-session-inactivity-timeout=1800
--telemetry-enabled=false
